# Generated by Django 2.1.4 on 2018-12-26 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='wxOpenId',
        ),
    ]
