# Generated by Django 2.1.4 on 2018-12-28 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_auto_20181226_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='wxNick',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
